baseURL = "https://hugo-paper.vercel.app/"
title = ".blog"
author = "Bruno Miguel"
copyright = "Os conteúdos, da minha autoria, neste blog estão sob a licença [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/)"
paginate = 5
languageCode = "pt"
DefaultContentLanguage = "pt"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
enableEmoji = true
preserveTaxonomyNames = true

# ------------------------------
theme = "paper"
#title = "Paper"

[params]
  twitter = 'brunomiguel'
  github = 'brunomiguel'
  #instagram = 'nan.xiaobei'
# ------------------------------

[markup.goldmark.renderer]
	unsafe = true

[taxonomies]
	category = "categories"
	tag = "tags"
	#series = "series"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "/about/"
    weight = 10
  
  [[menu.main]]
    identifier = "antinonio"
    name = "Lista Antonónio"
    url = "https://github.com/brunomiguel/antinonio/"
    weight = 20

  [[menu.main]]
    identifier = "userrepository"
    name = "Userrepository"
    url = "https://userrepository.eu/"
    weight = 30

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
