baseURL: "/"
title: .blog
paginate: 4
theme: hugo-PaperMod

languageCode: "pt"
DefaultContentLanguage: "pt"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

menu:
    main:
        - name: Arquivo
          url: arquivo
          weight: 2
        - name: Pesquisa
          url: search/
          weight: 1
        - name: Tags
          url: tags/
          weight: 4
        - name: Categorias
          url: categories/
          weight: 3
        - name: Privacidade
          url: privacidade/
          weight: 5

#languages:
#    en:
#        languageName: "English"
#        weight: 1
#        menu:
#            main:
#                - name: Archive
#                  url: archives
#                  weight: 5
#                - name: Search
#                  url: search/
#                  weight: 10
#                - name: Tags
#                  url: tags/
#                  weight: 10
#                - name: Categories
#                  url: categories/
#                  weight: 10
#
#    fr:
#        languageName: ":fr:"
#        languageAltTitle: French
#        weight: 2
#        title: PaperModL2
#        profileMode:
#            enabled: true
#            title: PaperMod
#            # imageUrl: "#"
#            # imageTitle: my image
#            # imageWidth: 120
#            # imageHeight: 120
#            subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
#            buttons:
#                - name: Blog
#                  url: posts
#                - name: Tags
#                  url: tags
#        menu:
#            main:
#                - name: Archive
#                  url: archives/
#                  weight: 5
#                - name: Tags
#                  url: tags
#                  weight: 10
#                - name: Categories
#                  url: categories
#                  weight: 10
#                - name: Series
#                  url: series
#                  weight: 10
#                - name: NullLink
#                  url: "#"
#                - name: NullLink2
#                  url: "#"
#                - name: NullLink3
#                  url: "#"
#
#    fa:
#        languagedirection: rtl
#        weight: 3
#        title: PaperMod RTL
#        homeInfoParams:
#            Title: "Hi there \U0001F44B"
#            Content: Welcome to RTL layout
#        menu:
#            main:
#                - name: Tags
#                  url: tags
#                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "O melhor blog do universo e, quiçá, de Portugal"
    author: Bruno Miguel
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: false
    comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: Bruno Miguel
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Olá 👋"
        Content: >
            Bem-vind@ ao melhor blog do mundo e, quiçá, de Portugal!

            - O blog aborda vários temas que me interessam, mas o foco é claramente tecnologia; específicamente, tecnologias abertas, vulgarmente conhecidas como _open-source_.

            - Puxa de uma cadeira e _assenta-te_.

    socialIcons:
        - name: RsS
          url: "index.xml"
        - name: twitter
          url: "https://twitter.com/brunomiguel"
        - name: github
          url: "https://github.com/adityatelange/hugo-PaperMod"
        #- name: KoFi
        #  url: "https://ko-fi.com/adityatelange"

    #editPost:
    #    URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #    Text: "Suggest Changes" # edit text
    #    appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    cover:
        responsiveImages: false
    #    hidden: true # hide everywhere but not in structured data
    #    hiddenInList: true # hide on list pages and home
    #    hiddenInSingle: true # hide on single page

    fuseOpts:
        isCaseSensitive: false
        shouldSort: false
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: false
        noClasses: false
        style: fruity

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
